import { Athlete } from "../_types/Athlete";

export const ATHLETES: Athlete[] = [
    {
        id: 1,
        firstName: "Teddy",
        lastName: "Riner",
        sport: "Judo",
        country: "France",
        countryCode: "FR",
        continentCode: "EU",
    },
    {
        id: 2,
        firstName: "Simone",
        lastName: "Biles",
        sport: "Gymnastics",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 3,
        firstName: "Novak",
        lastName: "Djokovic",
        sport: "Tennis",
        country: "Serbia",
        countryCode: "RS",
        continentCode: "EU",
    },
    {
        id: 4,
        firstName: "Katie",
        lastName: "Ledecky",
        sport: "Swimming",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 5,
        firstName: "Kevin",
        lastName: "Durant",
        sport: "Basketball",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 6,
        firstName: "Naomi",
        lastName: "Osaka",
        sport: "Tennis",
        country: "Japan",
        countryCode: "JP",
        continentCode: "AS",
    },
    {
        id: 7,
        firstName: "Shelly-Ann",
        lastName: "Fraser-Pryce",
        sport: "Athletics",
        country: "Jamaica",
        countryCode: "JM",
        continentCode: "NA",
    },
    {
        id: 8,
        firstName: "Tom",
        lastName: "Daley",
        sport: "Diving",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 9,
        firstName: "Allyson",
        lastName: "Felix",
        sport: "Athletics",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 10,
        firstName: "Armand",
        lastName: "Duplantis",
        sport: "Athletics",
        country: "Sweden",
        countryCode: "SE",
        continentCode: "EU",
    },
    {
        id: 11,
        firstName: "Marta",
        lastName: "Vieira da Silva",
        sport: "Soccer",
        country: "Brazil",
        countryCode: "BR",
        continentCode: "SA",
    },
    {
        id: 12,
        firstName: "Caeleb",
        lastName: "Dressel",
        sport: "Swimming",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 13,
        firstName: "Karsten",
        lastName: "Warholm",
        sport: "Athletics",
        country: "Norway",
        countryCode: "NO",
        continentCode: "EU",
    },
    {
        id: 14,
        firstName: "Ashleigh",
        lastName: "Barty",
        sport: "Tennis",
        country: "Australia",
        countryCode: "AU",
        continentCode: "OC",
    },
    {
        id: 15,
        firstName: "Hidilyn",
        lastName: "Diaz",
        sport: "Weightlifting",
        country: "Philippines",
        countryCode: "PH",
        continentCode: "AS",
    },
    {
        id: 16,
        firstName: "Pau",
        lastName: "Gasol",
        sport: "Basketball",
        country: "Spain",
        countryCode: "ES",
        continentCode: "EU",
    },
    {
        id: 17,
        firstName: "Elena",
        lastName: "Delle Donne",
        sport: "Basketball",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 18,
        firstName: "Florent",
        lastName: "Manaudou",
        sport: "Swimming",
        country: "France",
        countryCode: "FR",
        continentCode: "EU",
    },
    {
        id: 19,
        firstName: "Sifan",
        lastName: "Hassan",
        sport: "Athletics",
        country: "Netherlands",
        countryCode: "NL",
        continentCode: "EU",
    },
    {
        id: 20,
        firstName: "Kevin",
        lastName: "Mayer",
        sport: "Decathlon",
        country: "France",
        countryCode: "FR",
        continentCode: "EU",
    },
    {
        id: 21,
        firstName: "Ellie",
        lastName: "Simmonds",
        sport: "Paralympic Swimming",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 22,
        firstName: "Neeraj",
        lastName: "Chopra",
        sport: "Javelin Throw",
        country: "India",
        countryCode: "IN",
        continentCode: "AS",
    },
    {
        id: 23,
        firstName: "Jessica",
        lastName: "Springsteen",
        sport: "Equestrian",
        country: "United States",
        countryCode: "US",
        continentCode: "AM",
    },
    {
        id: 24,
        firstName: "Kanoa",
        lastName: "Igarashi",
        sport: "Surfing",
        country: "Japan",
        countryCode: "JP",
        continentCode: "AS",
    },
    {
        id: 25,
        firstName: "Dina",
        lastName: "Asher-Smith",
        sport: "Athletics",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 26,
        firstName: "Tadej",
        lastName: "Pogacar",
        sport: "Cycling",
        country: "Slovenia",
        countryCode: "SI",
        continentCode: "EU",
    },
    {
        id: 27,
        firstName: "Letesenbet",
        lastName: "Gidey",
        sport: "Athletics",
        country: "Ethiopia",
        countryCode: "ET",
        continentCode: "AF",
    },
    {
        id: 28,
        firstName: "Carissa",
        lastName: "Moore",
        sport: "Surfing",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 29,
        firstName: "Christian",
        lastName: "Coleman",
        sport: "Athletics",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 30,
        firstName: "Milena",
        lastName: "Rašić",
        sport: "Volleyball",
        country: "Serbia",
        countryCode: "RS",
        continentCode: "EU",
    },
    {
        id: 31,
        firstName: "Janja",
        lastName: "Garnbret",
        sport: "Sport Climbing",
        country: "Slovenia",
        countryCode: "SI",
        continentCode: "EU",
    },
    {
        id: 32,
        firstName: "Shan",
        lastName: "Lin",
        sport: "Table Tennis",
        country: "China",
        countryCode: "CN",
        continentCode: "AS",
    },
    {
        id: 33,
        firstName: "Eliud",
        lastName: "Kipchoge",
        sport: "Marathon",
        country: "Kenya",
        countryCode: "KE",
        continentCode: "AF",
    },
    {
        id: 34,
        firstName: "Tadej",
        lastName: "Pogacar",
        sport: "Cycling",
        country: "Slovenia",
        countryCode: "SI",
        continentCode: "EU",
    },
    {
        id: 35,
        firstName: "Julius",
        lastName: "Yego",
        sport: "Javelin",
        country: "Kenya",
        countryCode: "KE",
        continentCode: "AF",
    },
    {
        id: 36,
        firstName: "Mallory",
        lastName: "Franklin",
        sport: "Canoe Slalom",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 37,
        firstName: "Tegan",
        lastName: "McGrady",
        sport: "Soccer",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 38,
        firstName: "Lydia",
        lastName: "Ko",
        sport: "Golf",
        country: "New Zealand",
        countryCode: "NZ",
        continentCode: "OC",
    },
    {
        id: 39,
        firstName: "Nafi",
        lastName: "Thiam",
        sport: "Heptathlon",
        country: "Belgium",
        countryCode: "BE",
        continentCode: "EU",
    },
    {
        id: 40,
        firstName: "Michael",
        lastName: "Phelps",
        sport: "Swimming",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 41,
        firstName: "Manuel",
        lastName: "Charr",
        sport: "Boxing",
        country: "Germany",
        countryCode: "DE",
        continentCode: "EU",
    },
    {
        id: 42,
        firstName: "Charlotte",
        lastName: "Dujardin",
        sport: "Equestrian",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 43,
        firstName: "Dominika",
        lastName: "Banevic",
        sport: "Breaking",
        country: "Lithuania",
        countryCode: "LT",
        continentCode: "EU",
    },
    {
        id: 44,
        firstName: "Nevin",
        lastName: "Harrison",
        sport: "Canoe Sprint",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 45,
        firstName: "Joe",
        lastName: "Choong",
        sport: "Modern Pentathlon",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 46,
        firstName: "Giselle",
        lastName: "Ansley",
        sport: "Hockey",
        country: "Great Britain",
        countryCode: "GB",
        continentCode: "EU",
    },
    {
        id: 47,
        firstName: "Alex",
        lastName: "Morgan",
        sport: "Soccer",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 48,
        firstName: "Victor",
        lastName: "Montalvo",
        sport: "Breaking",
        country: "United States",
        countryCode: "US",
        continentCode: "NA",
    },
    {
        id: 49,
        firstName: "Hidilyn",
        lastName: "Diaz",
        sport: "Weightlifting",
        country: "Philippines",
        countryCode: "PH",
        continentCode: "AS",
    }
];
