export const COUNTRIES = [
    { name: "France", countryCode: "FR", continentCode: "EU" },
    { name: "United States", countryCode: "US", continentCode: "NA" },
    { name: "Serbia", countryCode: "RS", continentCode: "EU" },
    { name: "Japan", countryCode: "JP", continentCode: "AS" },
    { name: "Jamaica", countryCode: "JM", continentCode: "NA" },
    { name: "Great Britain", countryCode: "GB", continentCode: "EU" },
    { name: "Sweden", countryCode: "SE", continentCode: "EU" },
    { name: "Brazil", countryCode: "BR", continentCode: "SA" },
    { name: "Norway", countryCode: "NO", continentCode: "EU" },
    { name: "Australia", countryCode: "AU", continentCode: "OC" },
    { name: "Philippines", countryCode: "PH", continentCode: "AS" },
    { name: "Spain", countryCode: "ES", continentCode: "EU" },
    { name: "Netherlands", countryCode: "NL", continentCode: "EU" },
    { name: "India", countryCode: "IN", continentCode: "AS" },
    { name: "Slovenia", countryCode: "SI", continentCode: "EU" },
    { name: "Ethiopia", countryCode: "ET", continentCode: "AF" },
    { name: "China", countryCode: "CN", continentCode: "AS" },
    { name: "Kenya", countryCode: "KE", continentCode: "AF" },
    { name: "New Zealand", countryCode: "NZ", continentCode: "OC" },
    { name: "Belgium", countryCode: "BE", continentCode: "EU" },
    { name: "Germany", countryCode: "DE", continentCode: "EU" },
    { name: "Lithuania", countryCode: "LT", continentCode: "EU" },
];
